#!/usr/bin/env php
<?php

die('stub');

if ($argc > 1) {
   array_shift($argv);

   foreach ($argv as $argument) {
      echo serialize($argument);
   }

   exit;
}

while (false !== ($line = fgets(STDIN))) {
   $line = unserialize($line);

   if (is_string($line) or is_numeric($line))
      echo $line;
   else
      print_r($line);
}
