cask_ensure  app-tamer
cask_ensure  dockertoolbox
cask_ensure  firefox
cask_ensure  heroku-toolbelt
cask_ensure  licecap
cask_ensure  lighttable
cask_ensure  mou
cask_ensure  murus
cask_ensure  openoffice
cask_ensure  phpstorm
cask_ensure  processing
cask_ensure  screenflow
cask_ensure  sketch
cask_ensure  vagrant
cask_ensure  virtualbox
